pull_request_rules:
  - name: automatic merge
    conditions:
      - label!=DNM
      - '#approved-reviews-by>=1'
      - 'status-success=Testing: Travis CI - Pull Request'
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
      dismiss_reviews: {}
      delete_head_branch: {}
  - name: automatic merge on skip ci
    conditions:
      - label!=DNM
      - title~=\[skip ci\]
      - '#approved-reviews-by>=2'
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
      dismiss_reviews: {}
      delete_head_branch: {}
